version: "3.3"
services:
    sonarqube:
        image: sonarqube:latest
        ports :
            - "9000:9000"
        networks: 
            - network_dev 
        volumes:
            - sonar-data:/opt/sonarqube/data
            - sonar-logs:/opt/sonarqube/logs
            - sonar-extension:/opt/sonarqube/extensions
 
volumes: 
    sonar-data
    sonar-logs
    sonar-extension
